---
- name: Loops Playbook
  hosts: client1
  become: yes
  
  tasks:
  - name: Hello
    debug: msg="Hello {{ item }}"
    with_items:
      - "Lee"
      - "Dlee"

  - name: Until
    shell:  cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false
