---
- name: Playbook for variables
  hosts: all
  become: yes
  
  vars:
    message1: Hello
    message2: World
  tasks:
  - name: Print message variable
    debug:
      var: message1
  - debug:
      msg: "Hi {{ message2 }}"
  - set_fact: full_message="{{ message1 }} {{ message2 }}"
  - debug:
      var: full_message
